### ISSUE TITLE
add a MariaDb connector to bonita-connector-database

### ISSUE THREAD

**Issue by corradocampisano** [Bonitasoft-Community/Build-Bonita#27]
Hi,
this would actually refer to the non-community core repo:
https://github.com/bonitasoft/bonita-connector-database

Given BonitaPortal lives in Tomcat and I could quite easily replace a MySql connection with a MariaDb connection in a Tomcat application, why not adding MariaDb to the db-connector-set?

That would allow Debian 10 ("buster") too, within the "supported OSes" (no more mysql there):
https://documentation.bonitasoft.com/bonita//hardware-and-software-requirements#toc1

Any chance to see that soon?

Cheers,
Corrado.

**Comment by amottier** [comment]
For Bonita feature requests please use the [dedicated Jira project](https://bonita.atlassian.net/browse/BCI).

Anyway I will answer your question quickly here.

First regarding supported OSes, we only listed OSes that are used in Bonitasoft testing environment. We need to limit the number of OSes used for testing to limit the time required to perform all the tests (with each OS - database combination). We know that Bonita can run on pretty much any OSes. I personally run Bonita on Debian 10 Buster flawlessly.

Regarding the inclusion of MariaDB connector it is true that it can be (probably easily) added to the list of database connectors. But this is currently not the priority for several reasons. First the database connectors are becoming less popular due to the [Business Data Model (BDM)](https://documentation.bonitasoft.com/bonita//define-and-deploy-the-bdm) feature. Second, if database connector is needed, we usually recommend to use the generic data source connector. Using data source connector allows to benefit from application server database connections pooling that can have a significant impact on performance.

The only chance to have MariaDB connector soon is if some external contributor send a pull request on https://github.com/bonitasoft/bonita-connector-database. It should be fairly easy to create the MariaDB connector as a copy of MySQL connector with a few edits.
